version: "3.1"

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: web-3
      MYSQL_USER: web-user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
